[package]
name = "icon"
version = "0.1.0"
edition = "2024"

[dependencies]
freedesktop_entry_parser = "1.3.0"
thiserror = "2.0.12"
xdg = "3.0.0"
log = { version = "0.4.27", optional = true }

[features]
"log" = ["dep:log"]

[dev-dependencies]
freedesktop-desktop-entry = "0.7.13"
